version: "3.8"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: avideo_db
    #tty: true
    environment:
      # - MYSQL_USER=root
      # - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=avideo
      - TZ=UTC
    expose:
      - 3306
    volumes:
      - ./storage/data:/var/lib/mysql
    networks:
      - app_net
    ports:
      - "0.0.0.0:3306:3306"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sqladmin
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - app_net
    restart: always

  web:
    depends_on:
      - db
    hostname: avideo_web
    build: .
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - TZ=UTC
    expose:
      - 80
      - 443
    volumes:
      - .:/var/www/avideo:rw
    networks:
      - app_net
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"


# Docker Networks
networks:
  app_net:
    driver: bridge
